### PR TITLE
7.1 Mapping of descriptors to OSGi properties

### PR DESCRIPTION
**Pull request by jhinkey**
Hey Neil!

Your descriptions of these OSGi properties is absolutely awesome! So helpful!! :-)

When you get a chance tomorrow, or when you're in the office, would you review their incorporation in the descriptor to OSGi property map doc?

Thanks in advance!
Jim

### CODE REVIEW

**Comment by ngriffin7a** [comment]
@jhinkey I rebased liferay-docs and pushed to my origin but the GitHub UI still shows that I'm behind by 250+ commits. I'll have to close this PR and work through corrections via JIRA.

**Comment by jhinkey** [comment]
OK. Sorry for the hassle. My descriptor commits are the most recent commits (8 commits).

But it's fine to update via JIRA. Whatever works. :-)

**Comment by ngriffin7a** [comment]
@jhinkey OK, sorry for all my mistakes. I think I've fixed all the JIRA descriptions and left you JIRA comments.

**Comment by jhinkey** [comment]
No problem. I'll make those changes now.

**Comment by jhinkey** [comment]
@ngriffin7a As a follow up commit, would it be OK to put the rows in alphabetical order by their XPaths?

**Pull request closed without merging**
