### PR TITLE
JSF Tutorials

### PR DESCRIPTION
**Pull request by codyhoag**
Hey Neil,

Could you review a few JSF tutorials I've created for accuracy? Also, feel free to suggest additional information that should be covered.

This PR contains a new tutorial on creating a very simple JSF portlet, and two others on Using the WAB Generator and calling services. For convenience, I've linked to them below:

[Getting Started with JSF Applications](https://github.com/codyhoag/liferay-docs/blob/jsf-tutorial/develop/tutorials/articles/110-portlets/jsf/01-getting-started-with-jsf-applications.markdown)
[Using the WAB Generator](https://github.com/codyhoag/liferay-docs/blob/jsf-tutorial/develop/tutorials/articles/110-portlets/jsf/using-the-wab-generator.markdown)
[Services in JSF](https://github.com/codyhoag/liferay-docs/blob/jsf-tutorial/develop/tutorials/articles/110-portlets/jsf/services-in-jsf.markdown)

Thanks!

### CODE REVIEW

**Comment by ngriffin7a** [comment]
@codyhoag In general, this is is very good material. Thanks so much for working on this. :)

Regarding "Getting Started with JSF Applications", while there is a lot of value in walking developers through each file step-by-step, I'm concerned that steps like "Create a portlet.xml file in the webapp/WEB-INF folder" are superfluous since executing the "mvn archetype:generate" command creates a project with all those files already setup.

**Comment by codyhoag** [comment]
Hey @ngriffin7a; thanks for the review!

This "creating a plugin from scratch" approach has been the message promoted by Rich and Jorge. We're trying to keep tooling out of tutorials, and instead, point to tool-specific docs. Therefore, we want to have very detailed docs on how to create something manually, and then point to the Maven archetypes for an easier way to do it. This way of doing things dives deeper into what the build tool generates automatically, and gives an explanation for why certain files are present.

Let me know if you have any further questions about this detail-oriented style. I'll send this on to Rich if you're OK with its contents.

**Comment by ngriffin7a** [comment]
@codyhoag The detailed approach has many benefits, but I think it would be nice to see a parallel tutorial that shows how to use `mvn archetype:generate` from the command line, and then maybe how to import the project into an IDE like Eclipse. At some point in the near future, a tutorial that shows how to click on File->New JSF Portlet in Liferay IDE should be possible as well.

**Comment by codyhoag** [comment]
@ngriffin7a definitely! I'm in discussions with Dave Truong about some Maven docs now, so I'll definitely document the `mvn archetype:generate` way. Still much to document in the Tooling/JSF world :sweat_smile:

**Comment by codyhoag** [comment]
Sent sez11a#1833. Thanks!

**Pull request closed without merging**
