### PR TITLE
JSF Guestbook Upgrade Fixes

### PR DESCRIPTION
**Pull request by codyhoag**
Hey Neil,

I was able to resolve the JSF portlet's inability to properly import the `com.liferay.docs.guestbook.service` package from the `*-api` module. This was due to the portlet having a package named exactly the same, causing conflicts. The WAB generator was unable to add it to the list of imports in the Manifest because it already had that package listed as a private package. This is now fixed (commit f20989ea13576f946ea09d7cdfa8ee70e50092ab).

I'm now having errors reported that look something like this:
```
15:51:34,495 ERROR [http-nio-8080-exec-1][render_portlet_jsp:131] null
com.liferay.portal.kernel.exception.NoSuchResourcePermissionException: {companyId=20116, name=com.liferay.docs.guestbook.model, primKey=20143, scope=4}
```
I'm hoping this is coming from the permissions not being configured yet (although it's a bit unexpected, since I've commented out a lot of the permissions logic).

Whenever you or someone on the team has time, could you update the permissions logic to follow the new way your team is promoting? Let me know if there are any additional errors.

Thanks!

### CODE REVIEW

**Comment by ngriffin7a** [comment]
@codyhoag Have you tried stopping the portal, deleting $LIFERAY_HOME/data/hsql, restarting, and redeploying? Perhaps that would make the `NoSuchResourcePermissionException` go away.

**Comment by codyhoag** [comment]
@ngriffin7a In detail, this is what happens:

On a brand new database, adding the portlet to a page throws errors related to [LPS-74553](https://issues.liferay.com/browse/LPS-74553). The only difference is this happens on initial startup, not redeploys. During portlet redeploys, I get the `NoSuchResourcePermissionException` described above.

Maybe the issue has to do with LPS-74553; I was assuming it was from an old permission class import, but maybe it goes deeper than that.

**Comment by ngriffin7a** [comment]
@codyhoag I recommend working with an older version of DXP (or 7.0 CE GA4) that does not suffer from LPS-74553. Also the Faces team does not have a "new way" of specifying permissions different than the training recommended for MVCPortlet. Finally is guestbook-service the correct place for the resource-actions with LR7? https://github.com/codyhoag/liferay-docs/blob/jsf-guestbook-upgrade/develop/tutorials/code/jsf-guestbook-workspace/modules/guestbook/guestbook-service/src/main/resources/META-INF/resource-actions/default.xml

**Comment by codyhoag** [comment]
@ngriffin7a 
1. Switching to 7.0 CE GA4 resolves the LPS-74553 issue, but the `NoSuchResourcePermissionExeption` issue remains.
2. I'm referring to the more "JSF-ish" way of doing permissions reported in [LRDOCS-3592](https://issues.liferay.com/browse/LRDOCS-3592). Is the JSF way the same as the MVC way?
3. That's a good question. In the MVC portlet, Rich included one in the `-web` ([here](https://github.com/liferay/liferay-docs/blob/master/develop/tutorials/code/com-liferay-docs-guestbook/modules/guestbook-web/src/main/resources/META-INF/resource-actions/default.xml)) and `-service` ([here](https://github.com/liferay/liferay-docs/blob/3458a483c0dec7e757f870cd9a21fff994093d43/develop/tutorials/code/com-liferay-docs-guestbook/modules/guestbook/guestbook-service/src/main/resources/META-INF/resource-actions/default.xml)) modules. I didn't include a `default.xml` in the JSF portlet, which may be causing issues. I'm just not really sure how to approach the permissioning in this sample. I'm leaning on your team's expertise in this area.

**Comment by ngriffin7a** [comment]
1. Good, recommend that you stick with 7.0 CE GA4 for now.
2. From a UI point of view, the Liferay Faces Portal project provides the `portal:permissionsURL` component in order to introduce URLs into EL variables that can be used in EL Expressions. I recommend that you study each of the use-cases in http://www.liferayfaces.org/web/guest/portal-showcase/-/portal-tag/portal/permissionsurl/general
3.  From a resource-actions point of view, there should be no difference between a JSF portlet and an MVC portlet. Recommend doing it the same way in both tutorials.

**Comment by codyhoag** [comment]
Ok, sounds good. When I find some time, I'll attempt to reconfigure the permissioning.

Does everything else look OK as far as best practices go? I'm going to start outlining the learning path but want to make sure no huge changes are required.

**Comment by ngriffin7a** [comment]
@codyhoag After you get the permission stuff reconfigured and working (such that no exceptions are thrown) I can do a code review of the entire portlet and incorporate recommended practices that are missing.

**Comment by codyhoag** [comment]
OK; will do. Thanks!

**Pull request closed without merging**
