### PR TITLE
LRDOCS-5739 LRDOCS-5740 LRDOCS-5742 more portlet descriptor properties 

### PR DESCRIPTION
**Pull request by jhinkey**
Here you go for review, Neil. The changes are in the last commit. Thanks.

https://issues.liferay.com/browse/LRDOCS-5739
https://issues.liferay.com/browse/LRDOCS-5740
https://issues.liferay.com/browse/LRDOCS-5742

### CODE REVIEW

**Comment by jhinkey** [comment]
Hold on. I'm gonna make another change.

**Comment by jhinkey** [comment]
Here you go. Ready.

**Comment by ngriffin7a** [comment]
@jhinkey Thanks Jim!

**Comment by ngriffin7a** [comment]
@jhinkey Thanks for adding preferences-validator in a commit.

**Comment by jhinkey** [comment]
Here it is, Neil! Thanks for reviewing!!

**Comment by ngriffin7a** [comment]
@jhinkey The value for javax.portlet.version is incorrect -- see my comment dated today (9/28) at https://issues.liferay.com/browse/LRDOCS-5208

**Comment by jhinkey** [comment]
@ngriffin7a Sorry about that. Please see my last commit. Thanks.

**Comment by ngriffin7a** [comment]
@jhinkey Looks good, thanks.

**Comment by jhinkey** [comment]
Thanks! Sent https://github.com/sez11a/liferay-docs/pull/3599

**Pull request closed without merging**
