### PR TITLE
LRDOCS-3518 JSF Portlet Upgrade tutorial

### PR DESCRIPTION
**Pull request by codyhoag**
Hey Neil,

Can you review the JSF portlet upgrade article that we discussed earlier this week? I kept it pretty simple and basically pointed readers to http://liferayfaces.org/.

I have two simple example JSF portlets (6.2 and 7.0 version of JSF Applicant) that I point to in the article. Can you verify that their POMs are following best practices? I had to do some editing to extract them from the `liferay-faces-bridle-impl` repo. The links in the article do not work for the sample portlets, but you can see them [here](https://drive.google.com/open?id=0BzY9sDrOQrQ2RmJ5Q3JPbTJ4aWc). I turned edit permissions on, so feel free to make any changes there, if necessary.

Thanks!

### CODE REVIEW

**Comment by codyhoag** [comment]
Hey Neil; here's the link to the article:

https://github.com/codyhoag/liferay-docs/blob/jsf-portlet-upgrade/develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/04-upgrading-portlet-plugins/05-upgrading-a-liferay-jsfportlet.markdown

**Comment by ngriffin7a** [comment]
Thanks @codyhoag I made one small editorial commit. Also, you might want to mention that the article assumes that you are starting with JSF 2.2 in Liferay 6.2 and simply moving to Liferay 7.0.

**Comment by codyhoag** [comment]
Thanks @ngriffin7a! Yeah, I'll mention that we're starting from JSF 2.2.

**Comment by codyhoag** [comment]
Merged. Thanks!

**Pull request closed without merging**
